#!/usr/bin/bash
emacs --with-profile doom --bg-daemon &
mpDris2 -c /home/b/.config/mpDris2/mpDris2.conf &
setxkbmap -model pc105 -layout us,pl -option grp:alt_shift_toggle

wait $!
tmux new-session -d 'emacsclient -s doom -nw -c $HOME'
tmux new-window 'btop +t'
tmux next
tmux -2 attach-session -d
