#!/usr/bin/python

import os
import sys

import getopt


local_dir="~/Library"
usb_dir="/run/media/b/ARCH_202105/backup/Library"


args = sys.argv
getopt.


for i in range(0, len(args) + 1):
    if args[i].startswith('-'):
        if args[i].startswith('--'):
            if args[i][:2].startswith('local'):
                local_dir=args[i+1]
            elif args[i][:2].startswith('usb'):
                usb_dir=args[i+1]
            else:

        else:
            if args[i][1:].startswith('local'):
                local_dir=args[i+1]
            elif args
